name: hackathon
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.3.0
  google_maps_flutter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          style: normal

  assets:
    - assets/images/carrot.jpg
    - assets/images/harvester.png
    - assets/images/weed.png
    - assets/images/wheat.png
    - assets/images/watering.png
    - assets/images/foreign_worker.jpg
    - assets/images/user.webp
    - assets/images/thai_guy.jpg
